 const ACTION_TYPES={
    CREATE:"CREATE_TODO",
    DELETE:"DELETE_TODO",
    TOOGLE:"TOOGLE_TODO",
    UPDATE:"UPDATE_TODO",
    SET:"SET",
    LOADING:"LOADING",
    ERROR:"ERROR"
}

export default  ACTION_TYPES;